name: deploy-devnet

on:
  push:
    branches: [development]
  repository_dispatch:
    types: deploy-devnet
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn run build-devnet
        env:
          CI: false
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_DEVNET }} --delete
      - uses: rtCamp/action-slack-notify@master
        env:
          SLACK_ICON_EMOJI: ':admission_tickets:'
          SLACK_USERNAME: ${{ secrets.AWS_S3_BUCKET.DEVNET }}
          SLACK_MESSAGE: ${{ secrets.AWS_S3_BUCKET.DEVNET }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
